global-bird-zenodo_palmyra:
  name: 'global_birds_palmyra'
  image_path: ['']
  image_extension: '.png'
  annotation_path: ''
  annotation_col_names: ['image_path', 'label', 'xmin', 'ymin', 'xmax', 'ymax']
  annotation_format: 'LTBR'
  annotation_type: "global_csv"
  formatting_method: "from_multiple_global_csv_to_labels"

global-bird-zenodo_mckellar:
  name: 'global_birds_mckellar'
  image_path: ['']
  image_extension: '.png'
  annotation_path: ''
  annotation_col_names: ['image_path', 'label', 'xmin', 'ymin', 'xmax', 'ymax']
  annotation_format: 'LTBR'
  annotation_type: "global_csv"
  formatting_method: "from_multiple_global_csv_to_labels"

