
global-bird-zenodo_newmexico:
  name: 'global_birds_newmexico'
  image_path: ['']
  image_extension: '.png'
  annotation_path: ''
  annotation_col_names: ['image_path', 'label', 'xmin', 'ymin', 'xmax', 'ymax']
  annotation_format: 'LTBR'
  test_val_split: {test: ['BDA_12C'], val: ['BDA_18A4_20181106_1']}
  formatting_method: "from_multiple_global_csv_to_labels"
