

usgs-awaterfowl:
  name: 'alaskawaterfowls-test'
  image_path: 'image'
  image_extension: '.JPG'
  annotation_path: 'annotations'
  annotation_type: "independant_csv"
  formatting_method: "from_ind_csv_to_labels"

albatross_penguins-drones:
  name: 'albatross_penguins'
  image_path: ''
  image_extension: '.png'
  annotation_path: ''
  annotation_type: ''
  formatting_method: "from_classes_csv_to_labels"

penguins_counting:
  name: 'penguins'
  image_path: ['Thomas']
  image_extension: '.png'
  annotation_path: ''
  annotation_type: ''
  formatting_method: "from_global_json_to_csv"

seabirds_africa:
  name: 'seabirds_africa'
  image_path: 'seabirds_rgb.tif'
  image_extension: '.tif'
  annotation_path: 'labels_birds_full.csv'
  formatting_method: "from_global_csv_for_tiff_to_labels"
