uav-waterfowl-thermal:
  name: 'uav_thermal_waterfowl'
  image_path: ['01_Posistive Image', '03_Negative Images']
  image_extension: '.tif'
  annotation_path: '02_GroundtruthLabelforPositive\Bounding Box Label.csv'
  annotation_col_names: ['imageFilename', '', 'x(column)', 'y(row)', 'width', 'height']
  annotation_format: 'XYWH'
  annotation_type: "global_csv"
  formatting_method: "from_global_csv_to_labels"


global-bird-zenondo_newmexico:
  name: 'global_birds_newmexico'
  image_path: ['']
  image_extension: '.png'
  annotation_path: ''
  annotation_col_names: ['image_path', 'label', 'xmin', 'ymin', 'xmax', 'ymax']
  annotation_format: 'LTBR'
  annotation_type: "global_csv"
  formatting_method: "from_multiple_global_csv_to_labels"

global-bird-zenodo_palmyra:
  name: 'global_birds_palmyra'
  image_path: ['']
  image_extension: '.png'
  annotation_path: ''
  annotation_col_names: ['image_path', 'label', 'xmin', 'ymin', 'xmax', 'ymax']
  annotation_format: 'LTBR'
  annotation_type: "global_csv"
  formatting_method: "from_multiple_global_csv_to_labels"

global-bird-zenodo_penguins:
  name: 'global_birds_penguins'
  image_path: ['']
  image_extension: '.png'
  annotation_path: ''
  annotation_col_names: ['image_path', 'label', 'xmin', 'ymin', 'xmax', 'ymax']
  annotation_format: 'LTBR'
  annotation_type: "global_csv"
  formatting_method: "from_multiple_global_csv_to_labels"

global-bird-zenodo_pfeifer:
  name: 'global_birds_pfeifer'
  image_path: ['']
  image_extension: '.png'
  annotation_path: ''
  annotation_col_names: ['image_path', 'label', 'xmin', 'ymin', 'xmax', 'ymax']
  annotation_format: 'LTBR'
  annotation_type: "global_csv"
  formatting_method: "from_multiple_global_csv_to_labels"

global-bird-zenodo_poland:
  name: 'global_birds_poland'
  image_path: ['']
  image_extension: '.png'
  annotation_path: ''
  annotation_col_names: ['image_path', 'label', 'xmin', 'ymin', 'xmax', 'ymax']
  annotation_format: 'LTBR'
  annotation_type: "global_csv"
  formatting_method: "from_multiple_global_csv_to_labels"


usgs-awaterfowl:
  name: 'alaskawaterfowls-test'
  image_path: 'image'
  image_extension: '.JPG'
  annotation_path: 'annotations'
  annotation_type: "independant_csv"
  formatting_method: "from_ind_csv_to_labels"

albatross_penguins-drones:
  name: 'albatross_penguins'
  image_path: ''
  image_extension: '.png'
  annotation_path: ''
  annotation_type: ''
  formatting_method: "from_classes_csv_to_labels"

penguins_counting:
  name: 'penguins'
  image_path: ['Thomas']
  image_extension: '.png'
  annotation_path: ''
  annotation_type: ''
  formatting_method: "from_global_json_to_csv"

seabirds_africa:
  name: 'seabirds_africa'
  image_path: 'seabirds_rgb.tif'
  image_extension: '.tif'
  annotation_path: 'labels_birds_full.csv'
  formatting_method: "from_global_csv_for_tiff_to_labels"
