usgs-awaterfowl:
  name: 'alaskawaterfowls-test'
  image_path: 'image'
  image_extension: '.JPG'
  annotation_path: 'annotations'
  annotation_type: "independant_csv"
  formatting_method: "from_ind_csv_to_labels"

uav-waterfowl-thermal:
  name: 'waterfowls-test'
  image_path: '00_UAV\01_ThermalImagesandGround Truth\01_Posistive Image'
  image_extension: '.tif'
  annotation_path: '00_UAV\01_ThermalImagesandGround Truth\02_GroundtruthLabelforPositive\Bounding Box Label.csv'
  annotation_type: "global_csv"
  formatting_method: "from_global_csv_to_labels"

global-bird-zenodo:
  name: 'global_birds'
  image_path: ''
  image_extension: '.png'
  annotation_path: ''
  annotation_type: "global_csv"
  formatting_method: "from_multiple_global_csv_to_labels"

albatross_penguins-drones:
  name: 'albatross_penguins'
  image_path: ''
  image_extension: '.png'
  annotation_path: ''
  annotation_type: ''
  formatting_method: "from_classes_csv_to_labels"

penguins_counting:
  name: 'penguins'
  image_path: ['Thomas']
  image_extension: '.png'
  annotation_path: ''
  annotation_type: ''
  formatting_method: "from_global_json_to_csv"
